machines:

  - name: nginx
    network:
      switch: sw0
      gateway: 10.0.0.1
      mac: "00:00:00:00:00:01"
      ip: "10.0.0.10"
    docker:
      image: nginx:stable
#      command: "echo 'hi'"
      env_file: docker.env
      environment:
        A: B
        TWO: "2"
      volumes:
        - source: ${PWD}/html
          target: /usr/share/nginx/html
        - source: docker.env
          target: /tmp/docker.env

  - name: nginx-clones
    docker:
      image: nginx:stable
      env_file: docker.env
      environment:
        B: A
        THREE: "3"
      volumes:
        - source: ${PWD}/clones_html
          target: /usr/share/nginx/html
      scaling:
        count: 2
        interfaces:
          sw0:
            clones: [0, 1]
            gateway: "10.0.0.1"
            ip_type: dynamic
            mac_range:
              from: "00:00:00:00:00:01"
              to: "00:00:00:00:00:02"

network:
  ovn:
    switches:

      sw0:
        subnet: "10.0.0.0/24"

      public:
        subnet: "172.16.1.0/24"
        ports:
          - name: ls-public
            localnet:
              network_name: public

    routers:

      lr0:
        ports:

          - name: lr0-sw0
            mac: "00:00:00:00:ff:01"
            gateway_ip: "10.0.0.1/24"
            switch: sw0

        static_routes:
          - prefix: "0.0.0.0/0"
            nexthop: "172.16.1.1"

        nat:
          - nat_type: snat
            external_ip: "172.16.1.200"
            logical_ip: "10.0.0.0/16"

        dhcp:
          - switch: sw0
            exclude_ips:
              from: "10.0.0.1"
              to: "10.0.0.20"
