machines:

  - name: server
    libvirt:
      cpus: 2
      memory_mb: 2048
      libvirt_type:
        cloud_image:
          name: ubuntu_20_04
          expand_gigabytes: 20
          context: ./context_folder
      scaling:
        count: 3
        shared_setup: shared_setup.sh
        clone_setup:
          - script: clone_setup.sh
            clones: [0, 1, 2]
        interfaces:
          sw0:
            clones: [0, 1, 2]
            gateway: "10.0.0.1"
            ip_type: dynamic
            mac_range:
              from: "00:00:00:00:00:01"
              to: "00:00:00:00:00:03"

network:
  ovn:
    switches:

      sw0:
        subnet: "10.0.0.0/24"

      public:
        subnet: "172.16.1.0/24"
        ports:
          - name: ls-public
            localnet:
              network_name: public

    routers:

      lr0:
        ports:

          - name: lr0-sw0
            mac: "00:00:00:00:ff:01"
            gateway_ip: "10.0.0.1/24"
            switch: sw0

        static_routes:
          - prefix: "0.0.0.0/0"
            nexthop: "172.16.1.1"

        nat:
          - nat_type: snat
            external_ip: "172.16.1.200"
            logical_ip: "10.0.0.0/16"

        dhcp:
          - switch: sw0
            exclude_ips:
              from: "10.0.0.1"
              to: "10.0.0.20"
