[package]
name = "kvm-compose"
version = "1.1.0"
authors = ["Bristol Cyber Security Group"]
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "kvm_compose_lib"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true}
thiserror = { workspace = true}
anyhow = { workspace = true}
reqwest = { workspace = true}
serde_json = { workspace = true}
rust-embed = {version = "8.0.0", features = ["debug-embed"]}
chrono = { workspace = true }
tracing = { workspace = true}
futures-util = { workspace = true}
tokio = { workspace = true}
tokio-tungstenite = { workspace = true}
kvm-compose-schemas = { path = "../kvm-compose-schemas" }
tera = { workspace = true }
lazy_static = { workspace = true }
rand = "0.8.5"
async-trait = { workspace = true }
glob = "0.3.1"
nix = { workspace = true }
rexpect = "0.6.0"
virt = { workspace = true }
tempfile = "3.17.1"
