---
- name: Configure Host File
  hosts: all
  tasks:
  - name: Check if ansible_default_ipv4 is available
    set_fact:
      default_ipv4_available: "{{ ansible_default_ipv4 is defined and ansible_default_ipv4.interface is defined }}"

  - name: Debug default_ipv4_available
    debug:
      var: default_ipv4_available


  - name: Check if host file is present
    ansible.builtin.stat:
      path: /var/lib/testbedos/config/host.json
    register: hostfile_check


  - name: Read the actual host file content
    ansible.builtin.slurp:
      path: /var/lib/testbedos/config/host.json
    register: actual_hostfile
    when: default_ipv4_available and hostfile_check.stat.exists

  - name: Define expected host file content
    set_fact:
      expected_hostfile: |
        {
          "ip": "10.50.0.1",
          "user": "{{ ansible_user_id }}",
          "identity_file": "/home/{{ ansible_user_id }}/.ssh/id_ed25519",
          "testbed_nic": "eth0",
          "main_interface": "{{ ansible_default_ipv4.interface | default('eth0') }}",
          "is_main_host": true,
          "ovn": {
            "chassis_name": "main",
            "bridge": "br-int",
            "encap_type": "geneve",
            "encap_ip": "10.50.0.1",
            "main_ovn_remote": "unix:/usr/local/var/run/ovn/ovnsb_db.sock",
            "client_ovn_remote": null,
            "bridge_mappings": [
              [
                "public",
                "br-ex",
                "172.16.1.1/24"
              ]
            ]
          }
        }
    when: default_ipv4_available and hostfile_check.stat.exists

  - name: Convert expected host file content to JSON string
    set_fact:
      expected_hostfile_json: "{{ expected_hostfile | to_json }}"
    when: default_ipv4_available and hostfile_check.stat.exists

  - name: Create or update host file with expected content
    ansible.builtin.copy:
      content: "{{ expected_hostfile_json }}"
      dest: /var/lib/testbedos/config/host.json
    become: yes
    when: default_ipv4_available and (not hostfile_check.stat.exists or not (actual_hostfile.content | b64decode | from_json == expected_hostfile_json | from_json))

  - name: Compare host file content with expected content
    ansible.builtin.debug:
      msg: "Host file exists and its content matches expected content"
    when: default_ipv4_available and hostfile_check.stat.exists and (actual_hostfile.content | b64decode | from_json == expected_hostfile_json | from_json)

  - name: Internet unavailable
    debug:
      msg: "Internet connection has not been established"
    when: not default_ipv4_available

