---
- name: Install Pre-Requisites and Libvirt
  hosts: all
  become: true
  tasks:
  - name: Include variables based on OS
    include_vars: "{{ lookup('first_found', {'files': ['../vars/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/main.yaml'], 'paths': ['.']}) }}"

  - name: Install packages
    ansible.builtin.package:
      name: "{{prereq_packages}}"
      state: latest

  - name: Confirm LibVirt is installed
    ansible.builtin.debug: 
      msg: "LibVirt is already installed"
    when: libvrt_check.stat.exists

