---
- name: Install Docker
  hosts: all
  tasks:

  - name: Gather installed package facts
    package_facts:
      manager: apt
    become: yes

  - name: Include variables based on OS
    include_vars: "{{ lookup('first_found', {'files': ['../vars/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/main.yaml'], 'paths': ['.']}) }}"

  - name: Install Docker using shell script
    shell: "{{docker_steps}}"
    become: yes
    when: "'docker-ce' not in ansible_facts.packages"

  - name: Confirm Docker is installed
    ansible.builtin.debug:
      msg: "Docker is already installed"
    when: "'docker-ce' in ansible_facts.packages"