- name: Check Status
  import_playbook: ../common/1.status.yaml
  
- name: Check Consent
  hosts: all
  become: true
  vars_prompt:
    - name: "install_pre"
      prompt: "Would you like to install the missing components? (Yes/No)"
      private: no
  tasks:

  - name: Convert install_pre to boolean
    set_fact:
      install_bool: "{{ (install_pre | lower) in ['yes', 'y', 'true'] }}"
    
- name: Install Pre-Requisites
  import_playbook: ../common/2.prereq.yaml
  when: install_bool

- name: Install OVN and OVS
  import_playbook: ../common/3.ovn.yaml
  when: install_bool

- name: Install Docker
  import_playbook: ../common/4.docker.yaml
  when: install_bool

- name: Install Android SDK
  import_playbook: ../common/5.android.yaml
  when: install_bool

- name: Install Rust
  import_playbook: ../common/6.rust.yaml
  when: install_bool

- name: Install PyEnv and Python 3.10.5
  import_playbook: ../common/7.pyenv.yaml
  when: install_bool

- name: Install Poetry
  import_playbook: ../common/8.poetry.yaml
  when: install_bool

- name: Configure Libvirt
  import_playbook: ../common/9.libvrt-conf.yaml
  when: install_bool

- name: Install Poetry Dependencies
  import_playbook: ../common/10.poetry-dep.yaml
  when: install_bool

- name: Build Documentation
  import_playbook: ../common/11.docs.yaml
  when: install_bool

- name: Install TUI
  import_playbook: ../common/12.tui.yaml
  when: install_bool

- name: Install KVM-Compose
  import_playbook: ../common/13.kvm-compose.yaml
  when: install_bool

- name: Install TestbedOS-server
  import_playbook: ../common/14.testbedos-server.yaml
  when: install_bool

- name: Install Privact Tools
  import_playbook: ../common/15.privacy-tools.yaml
  when: install_bool

- name: Configure Host File
  import_playbook: ../common/16.host-file.yaml
  when: install_bool

- name: Configure qemu.conf
  import_playbook: ../common/17.qemu-conf.yaml
  when: install_bool

- name: Check Status
  import_playbook: ../common/1.status.yaml

- name: Confirm Completion of Installation
  hosts: all
  tasks:
   - name: Announcement
     debug:
       msg:
        - "Installation Complete."
        - "This script should have configured Testbed-OS to work in Singleton mode"
        - "Unexpected errors can usually be attributed to missing installations and/or dependencies not being listed in PATH"
        - "To start the Testbed-OS Server using - sudo testbedos-server main"
        - "For further information consult online documentation: https://testbedos.org/"
