{
 "title": "testbed guest resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "proj_n", "label": "project_name" },
   { "name": "guest_n", "label": "guest name" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage % (Per Client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage %",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "testbed_guest_cpu{project=\"$proj_n\", guest_name=\"$guest_n\"}",
       "legendFormat": "{{guest_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage % (Per Client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage %",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "testbed_guest_memory{project=\"$proj_n\", guest_name=\"$guest_n\"}",
       "legendFormat": "{{guest_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage % (All Clients)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage % (All Clients)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "testbed_guest_cpu{project=\"$proj_n\"}",
       "legendFormat": "{{guest_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory Usage % (All Clients)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Memory Usage % (All Clients)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "testbed_guest_memory{project=\"$proj_n\"}",
     "legendFormat": "{{guest_name}}"
    }
   ]
  }
 ]
}