name: Rust Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run cargo check
      working-directory: ./testbed-os/kvm-compose
      run: cargo check --all-targets

    - name: Run cargo clippy
      working-directory: ./testbed-os/kvm-compose
      run: cargo clippy --all-targets -- -D warnings
