name: rust-test

on: [pull_request, workflow_dispatch]

jobs:
  run-cargo-test:
    name: Cargo Test
    runs-on: [self-hosted]

    container:
      image: rust:latest
      options: --user root

    steps:
      - uses: actions/checkout@v6
      - run: apt-get update && apt-get install libvirt-dev -y
      - run: cd kvm-compose && cargo test

  run-cleanup:
    name: Cargo Test Cleanup
    runs-on: [self-hosted]
    steps:
      # clear the workspace including the cloned repo to prevent any leftover artefacts that might affect
      # a following workflow
      - name: post-test cleanup
        run: sudo rm -rf ${{ github.workspace }} || true
        if: always()
