name: rust-test

on: [push, pull_request, workflow_dispatch]

jobs:
  run-cargo-test:
    name: Cargo Test
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cd kvm-compose && cargo test
