name: test-harness

on: [pull_request]

jobs:
  run-test-harness:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: build-harness-image
        run: |
          cd test-harness && sudo docker image build -t test-harness:dev .
      - name: run-test-harness
        run: |
          cd test-harness && python --version
      - name: cleanup
        run: |
          docker image rm test-harness:dev
