name: test-harness

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

# This only works on main/default branches?
#on:
#  workflow_run:
#    workflows: ["rust-test"]
#    types: [completed]


jobs:
  run-test-harness:
    runs-on: [self-hosted]
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: build-harness-image
        run: |
          cd test-harness && docker image build -t test-harness:${{ github.event.pull_request.head.sha }} .
      - name: run-test-harness
        run: |
          cd test-harness && docker run \
            -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
            -v /var/lib/libvirt/images:/var/lib/libvirt/images --network=host \
            -e COMMIT_HASH=${{ github.event.pull_request.head.sha }} --rm test-harness:${{ github.event.pull_request.head.sha }}
      - name: cleanup
        run: |
          docker image rm test-harness:${{ github.event.pull_request.head.sha }}
